module.exports = {

  // AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// WORK ACTIONS
	RECEIVE_WORKS_DATA: "RECEIVE_WORKS_DATA",
	AWAIT_NEW_WORK_RESPONSE: "AWAIT_NEW_WORK_RESPONSE",
	RECEIVE_NEW_WORK_RESPONSE: "RECEIVE_NEW_WORK_RESPONSE",
	START_WORK_EDIT: "START_WORK_EDIT",
	FINISH_WORK_EDIT: "FINISH_WORK_EDIT",
  SUBMIT_WORK_EDIT: "SUBMIT_WORK_EDIT",

  // ARTIST ACTIONS
	RECEIVE_ARTISTS_DATA: "RECEIVE_ARTISTS_DATA",
	AWAIT_NEW_ARTIST_RESPONSE: "AWAIT_NEW_ARTIST_RESPONSE",
	RECEIVE_NEW_ARTIST_RESPONSE: "RECEIVE_NEW_ARTIST_RESPONSE",
	START_ARTIST_EDIT: "START_ARTIST_EDIT",
	FINISH_ARTIST_EDIT: "FINISH_ARTIST_EDIT",
  SUBMIT_ARTIST_EDIT: "SUBMIT_ARTIST_EDIT",

  //USERPROFILE ACTIONS
	RECEIVE_USERPROFILES_DATA: "RECEIVE_USERPROFILES_DATA",
	AWAIT_NEW_USERPROFILE_RESPONSE: "AWAIT_NEW_USERPROFILE_RESPONSE",
	RECEIVE_NEW_USERPROFILE_RESPONSE: "RECEIVE_NEW_USERPROFILE_RESPONSE",
	START_USERPROFILE_EDIT: "START_USERPROFILE_EDIT",
	FINISH_USERPROFILE_EDIT: "FINISH_USERPROFILE_EDIT",
  SUBMIT_USERPROFILE_EDIT: "SUBMIT_USERPROFILE_EDIT",
};


